### ISSUE TITLE
Blank fft/waterfall and changing freqs within sdrpp issue

### ISSUE THREAD

**Issue by alphafox02** [fosatech/Raven#2]
Just doing a quick test right now with the latest source using the venv setup. I have Firefox open and can see that the two RTLSDRs are started after setting the correct config. However, I've seen nothing in terms of an fft/waterfall etc on the STK Sweep main page. Inspecting the page shows

```
Uncaught NS_ERROR_FAILURE: 
    drawRow http://localhost:5000/static/js/rtlDataDisplay.js:673
    <anonymous> http://localhost:5000/static/js/rtlDataDisplay.js:839
```

I also noticed on my end where I try to start SDR++ even after wiped .config settings, it refuses to open since it pukes on -6 interface claimed (rtlsdrs in use). However, if I stop STK Sweep/TCP server and then open SDR++ it's okay.

With SDR++ opened and then going back and starting up the sweep/tcp server I can control left click on black area (I see freq changing on the left pane of stk) and the frequency changes in SDR++ but the actual listed freq/freq numbers do not. Likely an issue where SDR++ is just not realizing the tcp server is changing the freq.

Besides those issues, seems to be working. Just curious if I should be trying another browser?

**Comment by 0x41tlas** [comment]
The first error is most likely due to your bin size being too low. It's just a rendering issue on the frontend that I'll patch soon, but for now do <scan size in MHz> * 0.12 to get your bin size in kHz.

For rtl-tcp, make sure that you select a different device that the one you're using for the wideband. It automatically chooses device #0 for the wideband, so pick a different one for your rtl-tcp instance.

**Comment by alphafox02** [comment]
I just came back up to say my bad, didn't do the math on that last block. Works fine after taking the difference in MHz and * 0.12.

Did select the other device and it is working, was just meaning to say that within sdrpp the fft/water does in fact change most likely to what I'm clicking on within stk sweep, but the actual numbers in SDR++ do not change.. if that makes sense. This is a recent build of SDR++ if that helps.

**Comment by 0x41tlas** [comment]
Yup, that's the current limitation with using rtl-tcp and a proxy. We'll work on a way to interface directly with SDR++ to fix that.
